[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.devnet]
todo_dapp = "HaH9whuijUtKQK7jr2Su5GNqRRPRDLUXQxEKoQ94VhfU"

[programs.localnet]
todo_dapp = "HaH9whuijUtKQK7jr2Su5GNqRRPRDLUXQxEKoQ94VhfU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
